### ISSUE TITLE
Reduce code duplication for IAP config

### ISSUE THREAD

**Issue by JoepdeJong** [WISVCH/gke-cluster#24]
Currently, the following config is needed to setup a page behind IAP:

```yaml
apiVersion: networking.gke.io/v1
kind: GCPBackendPolicy
metadata:
  name: listmonk-backend-policy
  namespace: default
spec:
  default:
    iap:
      enabled: true
      oauth2ClientSecret:
        name: iap-secret
      clientID: 966138216790-us6sue108a879v3vk2om9inn3ftpobkg.apps.googleusercontent.com
  targetRef:
    group: ""
    kind: Service
    name: listmonk
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: listmonk-route
  namespace: default
spec:
  parentRefs:
  - kind: Gateway
    name: gateway
  hostnames:
  - listmonk.wisv.ch
  rules:
  - backendRefs:
    - name: listmonk
      port: 80
---
apiVersion: v1
kind: Service
metadata:
  name: listmonk
  namespace: default
spec:
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 8000
  selector:
    run: listmonk
  type: ClusterIP
---
apiVersion: networking.gke.io/v1
kind: HealthCheckPolicy
metadata:
  namespace: default
  name: listmonk
spec:
  default:
    config:
      type: HTTP
      httpHealthCheck:
        port: 8000
        requestPath: /actuator/health/liveness
    logConfig:
      enabled: true
  targetRef:
    group: ""
    kind: Service
    name: listmonk
```

Maybe we can make a default template for this?
